FROM golang:1.7-alpine

RUN apk update && apk add git

RUN go get -d github.com/Nexenta/nedge-docker-nfs/... && cd $GOPATH/src/github.com/Nexenta/nedge-docker-nfs && git checkout origin/stable/v17 && go get github.com/Nexenta/nedge-docker-nfs/...
